# Generated by Codex on 2026-04-22

from django.db import migrations, models


def seed_products(apps, schema_editor):
    Product = apps.get_model("todolist", "Product")
    products = [
        {
            "name": "Neem Face Wash",
            "slug": "neem-face-wash",
            "category": "Skin Care",
            "short_description": "A herbal face wash for gentle daily cleansing.",
            "description": "Made with neem-inspired care for oily and acne-prone skin to support a fresh, balanced routine.",
            "price": "850.00",
            "stock": 18,
            "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80",
            "is_featured": True,
            "is_active": True,
        },
        {
            "name": "Herbal Massage Oil",
            "slug": "herbal-massage-oil",
            "category": "Body Care",
            "short_description": "Comforting massage oil for body relaxation.",
            "description": "A soothing herbal oil blend designed for light massage, body relief, and a calming evening routine.",
            "price": "1200.00",
            "stock": 12,
            "image_url": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80",
            "is_featured": True,
            "is_active": True,
        },
        {
            "name": "Immunity Support Syrup",
            "slug": "immunity-support-syrup",
            "category": "Wellness",
            "short_description": "Daily wellness syrup crafted for family support.",
            "description": "A natural wellness syrup intended to complement healthy routines and seasonal care.",
            "price": "1450.00",
            "stock": 20,
            "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80",
            "is_featured": True,
            "is_active": True,
        },
        {
            "name": "Digestive Care Tea",
            "slug": "digestive-care-tea",
            "category": "Wellness",
            "short_description": "Light herbal tea blend for post-meal comfort.",
            "description": "A calming tea blend created for customers who want a warm, natural addition to digestive support routines.",
            "price": "650.00",
            "stock": 30,
            "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
            "is_featured": False,
            "is_active": True,
        },
    ]
    for product in products:
        Product.objects.update_or_create(slug=product["slug"], defaults=product)


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_alter_task_is_completed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("payment_method", models.CharField(choices=[("cod", "Cash on delivery"), ("bank", "Bank transfer")], default="cod", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=220)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="items", to="todolist.customerorder")),
                ("product", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="order_items", to="todolist.product")),
            ],
        ),
        migrations.RunPython(seed_products, migrations.RunPython.noop),
    ]
